### ISSUE TITLE
какой дефолтный тип джоина? что будет если у нас 100 сорсов в таблице, но только 3 из них имеют кампании?

### ISSUE THREAD

**Issue by Kirill-Shkodkin** [EliriaT/go-tasks#1]
https://github.com/EliriaT/go-tasks/blob/df56e181d8ac884d23343853a1d04aed6eb1b18a/hw1.sql#L3

**Comment by EliriaT** [comment]
The default type of the join is inner join. In case only 3 sources have associated campaigns, the query will not show the sources with 0 campaigns because of the inner join.

The query was fixed to also show sources with 0 campaigns:
 https://github.com/EliriaT/go-tasks/commit/d6f7429544b9c656a7746bc7a44e8be7ec646513
